Repository hetznercloud/cli, pull requests merged in 2022-11, with the labels that each got.

#414 fix: error when generating mocks
  internal/hcapi2/client.go
  internal/hcapi2/mock/client.go
  internal/hcapi2/mock/mock_gen.go
  internal/hcapi2/mock/zz_certificate_client_mock.go
  internal/hcapi2/mock/zz_datacenter_client_mock.go
  internal/hcapi2/mock/zz_firewall_client_mock.go
  internal/hcapi2/mock/zz_floating_ip_client_mock.go
  internal/hcapi2/mock/zz_image_client_mock.go
  internal/hcapi2/mock/zz_iso_client_mock.go
  internal/hcapi2/mock/zz_loadbalancer_client_mock.go
  internal/hcapi2/mock/zz_loadbalancer_type_client_mock.go
  internal/hcapi2/mock/zz_location_client_mock.go
  internal/hcapi2/mock/zz_network_client_mock.go
  internal/hcapi2/mock/zz_placement_group_client_mock.go
  internal/hcapi2/mock/zz_primary_ip_client_mock.go
  internal/hcapi2/mock/zz_rdns_client_mock.go
  internal/hcapi2/mock/zz_server_client_mock.go
  internal/hcapi2/mock/zz_server_type_client_mock.go
  internal/hcapi2/mock/zz_ssh_key_client_mock.go
  internal/hcapi2/mock/zz_volume_client_mock.go
  internal/hcapi2/mock_gen.go
  internal/hcapi2/zz_certificate_client_base.go
  internal/hcapi2/zz_datacenter_client_base.go
  internal/hcapi2/zz_firewall_client_base.go
  internal/hcapi2/zz_floating_ip_client_base.go
  internal/hcapi2/zz_image_client_base.go
  internal/hcapi2/zz_iso_client_base.go
  internal/hcapi2/zz_loadbalancer_client_base.go
  internal/hcapi2/zz_loadbalancer_type_client_base.go
  internal/hcapi2/zz_location_client_base.go
  internal/hcapi2/zz_network_client_base.go
  internal/hcapi2/zz_placement_group_client_base.go
  internal/hcapi2/zz_primary_ip_client_base.go
  internal/hcapi2/zz_rdns_client_base.go
  internal/hcapi2/zz_server_client_base.go
  internal/hcapi2/zz_server_type_client_base.go
  internal/hcapi2/zz_ssh_key_client_base.go
  internal/hcapi2/zz_volume_client_base.go
  internal/testutil/fixture.go
Labels: bug

#413 chore: update hcloud-go to v1.37.0
  go.mod
  go.sum
  internal/hcapi2/mock/zz_primary_ip_client_mock.go
  internal/hcapi2/mock/zz_server_client_mock.go
  internal/hcapi2/zz_primary_ip_client_base.go
  internal/hcapi2/zz_server_client_base.go
Labels: dependencies

#415 fix: primary-ip list returns max 50 items
  internal/cmd/primaryip/list.go
  internal/cmd/primaryip/list_test.go
Labels: bug

#420 Adding an age column to the cli, closes #417
  internal/cmd/certificate/list.go
  internal/cmd/floatingip/list.go
  internal/cmd/image/list.go
  internal/cmd/loadbalancer/list.go
  internal/cmd/network/list.go
  internal/cmd/network/list_test.go
  internal/cmd/placementgroup/list.go
  internal/cmd/placementgroup/list_test.go
  internal/cmd/primaryip/list.go
  internal/cmd/primaryip/list_test.go
  internal/cmd/server/list.go
  internal/cmd/sshkey/list.go
  internal/cmd/util/util.go
  internal/cmd/util/util_internal_test.go
  internal/cmd/volume/list.go
Labels: feature

#426 feat(completion): read network zones from API
  internal/cmd/loadbalancer/create.go
  internal/cmd/network/add_subnet.go
  internal/hcapi/location.go
  internal/state/helpers.go
Labels: feature
