Repository hetznercloud/cli, pull requests merged in 2023-10, with the labels that each got.

#555 feat(iso): support deprecation info API
  go.mod
  go.sum
  internal/cmd/iso/describe.go
Labels: feature

#564 feat(primary-ip): enable/disable-protection accept levels as arguments
  internal/cmd/primaryip/disable_protection.go
  internal/cmd/primaryip/enable_protection.go
Labels: feature

#567 feat: add --enable-protection flag to "create" commands
  internal/cmd/floatingip/create.go
  internal/cmd/loadbalancer/create.go
  internal/cmd/network/create.go
  internal/cmd/primaryip/create.go
  internal/cmd/server/create.go
  internal/cmd/volume/create.go
Labels: feature

#568 feat(server): add --enable-backup flag to "create" command
  internal/cmd/server/create.go
Labels: feature

#570 test(server): test --enable-protection and --enable-backup in "create" command
  internal/cmd/server/create_test.go
Labels: test

#571 refactor: export list commands and only pass flags to ListCmd.Fetch
  internal/cmd/base/list.go
  internal/cmd/certificate/certificate.go
  internal/cmd/certificate/list.go
  internal/cmd/datacenter/datacenter.go
  internal/cmd/datacenter/list.go
  internal/cmd/firewall/firewall.go
  internal/cmd/firewall/list.go
  internal/cmd/floatingip/floatingip.go
  internal/cmd/floatingip/list.go
  internal/cmd/image/image.go
  internal/cmd/image/list.go
  internal/cmd/iso/iso.go
  internal/cmd/iso/list.go
  internal/cmd/loadbalancer/list.go
  internal/cmd/loadbalancertype/list.go
  internal/cmd/location/list.go
  internal/cmd/location/location.go
  internal/cmd/network/list.go
  internal/cmd/placementgroup/list.go
  internal/cmd/primaryip/list.go
  internal/cmd/primaryip/list_test.go
  internal/cmd/primaryip/primaryip.go
  internal/cmd/server/list.go
  internal/cmd/servertype/list.go
  internal/cmd/sshkey/list.go
  internal/cmd/sshkey/sshkey.go
  internal/cmd/volume/list.go
  internal/cmd/volume/volume.go
Labels: refactor

#574 fix(floating-ip): list command only returns first 50 entries
  internal/cmd/floatingip/list.go
Labels: bug

#573 feat(iso): allow to filter list by type (public, private)
  internal/cmd/iso/list.go
Labels: feature

#578 fix(image): list does not parse "type" flag correctly
  internal/cmd/image/list.go
Labels: bug

#579 fix: list outputs null instead of empty array when listing in JSON
  internal/cmd/certificate/list.go
  internal/cmd/datacenter/list.go
  internal/cmd/firewall/list.go
  internal/cmd/floatingip/list.go
  internal/cmd/image/list.go
  internal/cmd/iso/list.go
  internal/cmd/loadbalancer/list.go
  internal/cmd/loadbalancertype/list.go
  internal/cmd/location/list.go
  internal/cmd/network/list.go
  internal/cmd/placementgroup/list.go
  internal/cmd/primaryip/list.go
  internal/cmd/server/list.go
  internal/cmd/servertype/list.go
  internal/cmd/sshkey/list.go
  internal/cmd/volume/list.go
Labels: bug

#580 feat: add "all list" command to list all available resources
  internal/cli/root.go
  internal/cmd/all/all.go
  internal/cmd/all/list.go
  internal/cmd/all/list_test.go
  internal/cmd/base/list.go
  internal/cmd/certificate/list.go
  internal/cmd/datacenter/list.go
  internal/cmd/firewall/list.go
  internal/cmd/floatingip/list.go
  internal/cmd/image/list.go
  internal/cmd/iso/list.go
  internal/cmd/loadbalancer/list.go
  internal/cmd/loadbalancertype/list.go
  internal/cmd/location/list.go
  internal/cmd/network/list.go
  internal/cmd/placementgroup/list.go
  internal/cmd/primaryip/list.go
  internal/cmd/server/list.go
  internal/cmd/servertype/list.go
  internal/cmd/sshkey/list.go
  internal/cmd/volume/list.go
Labels: feature

#589 fix: "create" actions were not awaited in some cases
  internal/cmd/firewall/create.go
  internal/cmd/floatingip/create.go
  internal/cmd/placementgroup/create.go
  internal/cmd/placementgroup/create_test.go
  internal/cmd/primaryip/create.go
  internal/cmd/primaryip/create_test.go
Labels: bug

#590 feat: print out IPs after they were created
  internal/cmd/floatingip/create.go
  internal/cmd/primaryip/create.go
  internal/cmd/primaryip/create_test.go
Labels: feature

#592 fix: static resource list commands only return first 50 entries
  internal/cmd/datacenter/list.go
  internal/cmd/loadbalancertype/list.go
  internal/cmd/location/list.go
  internal/cmd/servertype/list.go
Labels: bug

#593 fix: inconsistent formatting in "describe" commands
  internal/cmd/certificate/describe.go
  internal/cmd/datacenter/describe.go
Labels: bug

#594 fix(primary-ip): list does now allow to output IP column
  internal/cmd/floatingip/list.go
  internal/cmd/primaryip/list.go
Labels: bug
