Repository hetznercloud/cli, pull requests merged in 2024-07, with the labels that each got.

#805 fix(config): ordering of list option values not preserved
  internal/cmd/config/add.go
  internal/cmd/config/add_test.go
  internal/cmd/util/util.go
  internal/cmd/util/util_test.go
  internal/state/config/options.go
Labels: bug

#817 refactor: use new price formatter
  internal/cmd/loadbalancertype/describe.go
  internal/cmd/loadbalancertype/describe_test.go
  internal/cmd/servertype/describe.go
  internal/cmd/servertype/describe_test.go
  internal/cmd/util/util.go
  internal/cmd/util/util_test.go
  internal/hcapi2/client.go
  internal/hcapi2/mock/client.go
  internal/hcapi2/mock/mock_gen.go
  internal/hcapi2/mock/zz_pricing_client_mock.go
  internal/hcapi2/pricing.go
Labels: refactor

#827 feat: new APIs for traffic pricings
  go.mod
  go.sum
  internal/cmd/loadbalancertype/describe.go
  internal/cmd/loadbalancertype/describe_test.go
  internal/cmd/servertype/describe.go
  internal/cmd/servertype/describe_test.go
  internal/cmd/servertype/list.go
  internal/cmd/servertype/list_test.go
Labels: feature
